name: ciao
channels:
  - conda-forge
  - https://cxc.cfa.harvard.edu/conda/ciao/

show_channel_urls: True

dependencies:
  - https://cxc.cfa.harvard.edu/conda/ciao/::sherpa
  - conda-forge::ultranest
  - conda-forge::coverage<7.0.0
  - conda-forge::coveralls==3.3.1
  - conda-forge::scipy
  - conda-forge::matplotlib>=3.5
  - conda-forge::h5py
  - conda-forge::astropy
  - conda-forge::requests
  - conda-forge::cython
  - conda-forge::tqdm
  - conda-forge::toml
  - conda-forge::joblib
